### ISSUE TITLE
which dataset do you use?

### ISSUE THREAD

**Issue by xingmimfl** [VectXmy/GANFIT.Pytorch#1]
it seems that you have successfully re-implemented ganfit :P.
which dataset do you use ? 300W_LP or others? 
do you have a plan to release this code ?

**Comment by VectXmy** [comment]
This is about a commercial project, I can't tell too much about it. The implementation is somewhat different from the paper.There are no open source plans for the time being.

**Comment by VectXmy** [comment]
the results in README are tested on 300wlp dataset, but you can use any other picture. no open sourse plans for the time being.
